#!/bin/bash
python experiment.py Trainer.name=full Trainer.save_dir=fs_baseline

python experiment.py Trainer.name=iterative Trainer.save_dir=iteractive_1/detach_false Iterations.num_iter=1 Arch.detach=false
python experiment.py Trainer.name=iterative Trainer.save_dir=iteractive_2/detach_false Iterations.num_iter=2 Arch.detach=false
python experiment.py Trainer.name=iterative Trainer.save_dir=iteractive_3/detach_false Iterations.num_iter=3 Arch.detach=false

python experiment.py Trainer.name=iterative Trainer.save_dir=iteractive_1/detach_true Iterations.num_iter=1 Arch.detach=true
python experiment.py Trainer.name=iterative Trainer.save_dir=iteractive_2/detach_true Iterations.num_iter=2 Arch.detach=true
python experiment.py Trainer.name=iterative Trainer.save_dir=iteractive_3/detach_true Iterations.num_iter=3 Arch.detach=true
