#!/bin/bash
export CUBLAS_WORKSPACE_CONFIG=:4096:8
export PYTHONOPTIMIZE=1
githash=$(git rev-parse HEAD)
githash=${githash:0:7}

save_dir=$1
python experiment.py Trainer.name=full Trainer.save_dir=$save_dir/$githash/fs_baseline

python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_1/detach_false Iterations.num_iter=1 Arch.detach=false
python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_2/detach_false Iterations.num_iter=2 Arch.detach=false
python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_3/detach_false Iterations.num_iter=3 Arch.detach=false
python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_4/detach_false Iterations.num_iter=4 Arch.detach=false

python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_1/detach_true Iterations.num_iter=1 Arch.detach=true
python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_2/detach_true Iterations.num_iter=2 Arch.detach=true
python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_3/detach_true Iterations.num_iter=3 Arch.detach=true
python experiment.py Trainer.name=iterative Trainer.save_dir=$save_dir/$githash/iteractive_4/detach_true Iterations.num_iter=4 Arch.detach=true
