Aggregator:
  alpha: 0.9
Arch:
  input_dim: 5
  num_classes: 4
Checkpoint: /home/jizong/UserSpace/Iterative-learning/up/runs/tmp
Data:
  labeled_data_ratio: 1
  name: acdc
  unlabeled_data_ratio: 0.0
GITHASH: 56749e7abcc0d5201d9928d21ec9712cd299aa91
Iterations:
  num_iter: 2
LabeledData:
  batch_size: 5
  num_workers: 5
  shuffle: true
Optim:
  lr: 1.0e-06
  name: Adam
  weight_decay: 1.0e-05
RandomSeed: 10
Scheduler:
  multiplier: 400
  warmup_max: 10
Trainer:
  device: cuda
  feature_importance:
  - 1
  - 0.5
  - 0.5
  feature_names:
  - Conv5
  - Up_conv3
  - Up_conv2
  max_epoch: 1000
  name: full
  num_batches: 200
  save_dir: tmp
UnlabeledData:
  batch_size: 10
  num_workers: 4
  shuffle: true
ValidationData:
  batch_size: 5
  num_workers: 1
  shuffle: true
