RandomSeed: 10

Arch:
  name: type1
  layer_dim: 112
  codec: encoder
  input_dim: 1
  num_classes: 4
  num_features: 32
  detach: false
  iter_to_use: 2

Optim:
  name: Adam
  lr: 0.0000005
  weight_decay: 0.00001

Iterations:
  num_iter: 3

Aggregator:
  alpha: 0.9

Scheduler:
  multiplier: 400
  warmup_max: 10

Data:
  name: acdc
  labeled_num_scans: 10

LabeledData:
  shuffle: true
  batch_size: 10
  num_workers: 6

ValidationData:
  shuffle: False
  batch_size: 5
  num_workers: 1

Trainer:
  name: iterative
  save_dir: tmp
  device: cuda
  num_batches: 300
  max_epoch: 50
  freeze_grad: [ Conv1, Conv5 ]







#Checkpoint: runs/test_pipeline