RandomSeed: 10

Arch:
  input_dim: 1
  num_classes: 4

Optim:
  name: Adam
  lr: 0.000001
  weight_decay: 0.00001

Iterations:
  num_iter : 2

Aggregator:
  alpha : 0.9

Scheduler:
  multiplier: 400
  warmup_max: 10

Data:
  name: acdc
  labeled_data_ratio: 1
  unlabeled_data_ratio: 0.00

LabeledData:
  shuffle: true
  batch_size: 5
  num_workers: 5

ValidationData:
  shuffle: true
  batch_size: 5
  num_workers: 1

UnlabeledData:
  shuffle: true
  batch_size: 10
  num_workers: 4

Trainer:
  feature_names: ["Conv5", "Up_conv3", "Up_conv2"]
  feature_importance: [1, 0.5, 0.5]
  name: full
  save_dir: tmp
  device: cuda
  num_batches: 500
  max_epoch: 100







#Checkpoint: runs/test_pipeline